default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000

development:
    <<: *default
    database: <%= "#{Rails.application.class.parent.name.underscore}_development" %>
    username: postgres
    password: password

staging:
    <<: *default
    database: <%= "#{Rails.application.class.parent.name.underscore}_development" %>
    username: postgres
    password: password
test: &test
    <<: *default
    database: <%= "#{Rails.application.class.parent.name.underscore}_test" %>

cucumber:
    <<: *test

#https://devcenter.heroku.com/articles/concurrency-and-database-connections#threaded-servers
production:
    adapter: postgresql
    url:  <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
