# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e18ede1d649986580393b88ef7342b6254165500fc7781b9f519234b133c1ebfa70a35fbf67b9683a14389274e85eab66b935b67d7943005396339460b014e18
  bitpay_button_strings:
    form_url: https://test.bitpay.com/checkout
    button_string: https://test.bitpay.com/cdn/en_US/bp-btn-pay-currencies.svg
    package_01: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoxaoRoZoi4K6gsx3xjpAtimL9C83vGymtgCPzP4GY1gdh5jed0W4gIMgdlL1DqZ54fJsKgaPfzahKe/4ilKKws6NT5LfFFxQrr5fNnQRsNG8Qj1SBu1oZ+u+qANolSe1kTDABK2A7HIsDIJCb/6uYN5r7xaCwztRrwiMoQms+Xqu8jFD7uM38eStgcHP7vKmGgHj6MkVkxp7GTkLtR9HeaGKzgjkjjn29Fr6vG21qHM/HJB00/2bEWbDUF0CpLR+6
    package_02: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoG+Y7OSy+gyeqEcCx6EhV+qasrMWWelIJYVdaXPsApVliGYwUdwB5uNjueQmh+Iy0xXS2n82FeM9yjbewHkEQBctDSfnvMEHWSOZF27/vb88+5wJk8D4cvaVFZucHRN6JD9vSCTKxhxGybYWqwDuEzjQE5jlLlII1dKBcssNYB/aCtHmV5ayc/yiUy8OfdwMeXdZ2JZd1hirzr9MUXGykvIQZ1vSEw6fxhjXoORPLmuUumzFVCIyitu4OBvEcDYGe
    package_03: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoyeBUMwgQqLlDEmCkgj4OmhBCe7puMlTuuWO21p12f0HSpcLtowXaCWeY948IVNTc+6r2ojShKduPhc94wSVtCqB4lVvGGGH7CelxW5XX01dIFypMHI354U9vkTTm/Jbq7lHp36YyIIrB6/4UI9UilKyyeCpeJXIZKqwZ1lyZFAke1VRxcjUUmQLU5u8XPnpV87lPyVnwYXFJJxdCY/Y4oli0KJPSaphnlduWYFuIRvd3y1sTl5E5HujYI7hAFcjh
    package_04: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoP8HdkfxzSsdA2GNhx1dvR6YyyWS+JoNGWaFWKWWX8DaJzg4b0EPkwMi1Cb0uKYOfgWWKu3+UeafwpCer7mxZUiARRa+zWviwPWJY28C3vk1phZ+8cBNWQEkuTncL2B+R70vKCLe98NJzkqsb6UewkyKSqO17KKU+2sZWuse1K+wIPIWL+MJa0pofx5K3kZ3ObTiKZgbIANgvfFPL9+CQFbKYEgi4d1pnC1frj4LKLUXlLRenAKAig++9WlHL7e3H
    package_05: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoxaoRoZoi4K6gsx3xjpAtigjqhaOmLJKS2hxhJEx59+dEe38MEPly/3PqdyCSlrEzTAWEzTnx+kvwo/7oGfRfrHj0ZJx/uIrKfkvYmeGyP9zmOZHZRlCHurMUnarntAIIvxm/qz+FJnZX17VQehPcWsX8L4vehrYQcYJsQyVkvPOlVcVYQUbGXfQ2fS6dhSUt2ZhweGw7zKgP7+e7+k4lO4UcDTpNukE4Fha8Sbibr/HBLKPdR9hMpcbLzr0xWA/gZieIe+V7xPOfjlhuQ5z4BA==
    package_06: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoG+Y7OSy+gyeqEcCx6EhV+rkARqqX2RKiLbEmaWOdwLYf1RL8pGZkA+Pgvp8mm2soqfoxun0Hq4HxE/8KvShL41xystCwS7aSMydVyKu7P3A4OTukTLAWTWyjFDIWFZAdRE48hKVo03C8Vg23ZCS8jCZbpuxZZC69uKAAWOulOxsQr0cH6vFKRkfAkgNLeAL3/+mHpoynRFVzLG9U+EiGGBMM1tL/8OtQFR5IxksyJhjIl/oQJwCntpnyXfMBVAkAzeqRPHA0yA/UE7QH6BPURw==
    package_07: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoP8HdkfxzSsdA2GNhx1dvR/N9Z8+sjY3dCNZsfQWCA5Xi2RLkM0uC6lwJ/79I3XGdtnQrlKX7JLp8JVILvYdiaWG8CQkxC7oqwh00bFS6QruKWawUpuNQmgNn+BfL1qcw6ZHgVLfLJ+/DaP/rr0ofkjkR6aPTVmKua2rsivj1Yy0bXW2mM6mce+PT3hrgacKr/g8EMr4iAoha4gDmyXetBuCTFi2R3+HyGx2BsNeFD4vPNw31IdZCQJ5SgU2WViQICSibskwy7hIX8pcl+ou2cw==
    package_08: ZauA8qbvEwgc5rKZT9lG94LN3eisVtvvMZqzhDz0nZ6wCXISi1uxcdwfEdC5BcDoxaoRoZoi4K6gsx3xjpAtipHuLuulFAyJSRpMcjhVkcP6F8TdxePCBQCe1zkZijzjB69sopra3SghrZLC+tBm0sT7k1zcByPJ50gm7nHCpqda8Mu5rPrCMXwsZOP74tRRkx6g1TWofbEphMzAaiPmiA+OChdIkUvVdE7XnmZzI6/QyO35z/wzcSgNmJoMpeYCVWytPZ0HEkYhbUR+Di2SpMWH1o2v+Iilbv6L3shfbSetylVpkFn1Y7NxNT4NtCQghvmhiF5cXilt0ILvUfH0kA==
test:
  secret_key_base: d1c36628f111be232985d395a20342e1e9288b4f9687d05a812cc9fc7138af776b6ee2e4c9cddeb5b242c7b1debbb65565cd260a4041410c9aa0d8e5014b95ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: e18ede1d649986580393b88ef7342b6254165500fc7781b9f519234b133c1ebfa70a35fbf67b9683a14389274e85eab66b935b67d7943005396339460b014e18
